---
- name: install uchiwa
  apt: name=uchiwa state=present
  when: ansible_os_family == 'Debian'

- name: install uchiwa
  yum: name=uchiwa state=present
  when: ansible_os_family == 'RedHat'

- name: enable uchiwa to survive reboot
  service: name=uchiwa enabled=yes

- name: create uchiwa config file
  template:
    src=uchiwa.json.j2
    dest=/etc/sensu/uchiwa.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify:
    - restart uchiwa service
