---
- hosts: all
  tasks:
     - group_by: key={{ ansible_os_family }}

- hosts: RedHat
  user: vagrant
  sudo: yes
  pre_tasks:
  - yum: name=libselinux-python state=present
  roles:
  - epel

- hosts: sensu_server_client
  user: vagrant
  vars:
    - sensu_install_server: true
    - sensu_install_client: true
    - sensu_client_hostname: "sensu-server-client"
    - sensu_client_address: "192.168.60.2"
  vars_files:
    - test-vars.yml
  roles:
    - redis
    - Mayeu.RabbitMQ
    - sensu

- hosts: sensu_server
  user: vagrant
  vars:
    - sensu_install_server: true
    - sensu_install_client: false
  vars_files:
    - test-vars.yml
  roles:
    - redis
    - sensu

- hosts: sensu_client
  user: vagrant
  vars:
    - sensu_install_server: false
    - sensu_install_client: true
    - sensu_client_hostname: "sensu-client"
    - sensu_client_address: "192.168.60.4"
  vars_files:
    - test-vars.yml
  roles:
    - sensu
