#!/bin/bash

# chkconfig: 345 90 90
# description: Sensu monitoring framework server

### BEGIN INIT INFO
# Provides:       sensu-server
# Required-Start: $remote_fs $network rabbitmq-server
# Required-Stop:  $remote_fs $network rabbitmq-server
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Sensu monitoring framework server
### END INIT INFO

/etc/init.d/sensu-service server $1

exit $?
